name: Deploy to Droplet
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:

env:
  HOST: ${{ secrets.DEPLOY_HOST }}
  USER: ${{ secrets.DEPLOY_USER }}
  PATH_ON_SERVER: ${{ secrets.DEPLOY_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Trust host (known_hosts)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Show keys loaded in agent (fingerprints)
        run: |
          ssh-add -L | ssh-keygen -lf - || (echo "No keys in agent"; exit 1)

      - name: Fingerprint of DEPLOY_KEY secret (should match server)
        shell: bash
        run: |
          umask 077
          printf "%s" "${{ secrets.DEPLOY_KEY }}" > id
          ssh-keygen -y -f id > id.pub
          echo "DEPLOY_KEY fingerprint:"
          ssh-keygen -lf id.pub
          rm -f id id.pub

      - name: SSH smoke test (verbose)
        run: |
          ssh -vvv $USER@$HOST 'echo GH-SSH-OK && whoami'

      - name: Rsync to _incoming (atomic)
        run: |
          set -e
          RELEASE="release-${{ github.sha }}"
          rsync -az --delete \
            --exclude=".git" --exclude=".github" \
            ./ "$USER@$HOST:$PATH_ON_SERVER/_incoming/$RELEASE/"

      - name: Flip symlink + reload Nginx
        run: |
          set -e
          RELEASE="release-${{ github.sha }}"
          ssh $USER@$HOST "set -e
            mv $PATH_ON_SERVER/_incoming/$RELEASE $PATH_ON_SERVER/releases/$RELEASE
            ln -sfn $PATH_ON_SERVER/releases/$RELEASE $PATH_ON_SERVER/current
            sudo /usr/sbin/nginx -t && sudo /usr/bin/systemctl reload nginx"
